name: Release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
      - name: Install geo
        run: go install -v github.com/metacubex/geo/cmd/geo@master
      - name: Download v2fly geosite and geoip
        run: |
          curl -L -o geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
          curl -L -o geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
      - name: Convert geosite and geoip to sing-box format
        run: |
          geo convert site -i v2ray -o sing -f geosite.db geosite.dat
          geo convert ip -i v2ray -o sing -f geoip.db geoip.dat
      - name: Make sing-rule-set
        run: |
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest \
              | grep tag_name \
              | cut -d ":" -f2 \
              | sed 's/\"//g;s/\,//g;s/\ //g;s/v//')
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/sing-box-${VERSION}-linux-amd64.tar.gz
          tar -xf sing-box.tar.gz
          rm -rf sing-box.tar.gz
          cp geosite.db sing-box-${VERSION}-linux-amd64/geosite.db
          cp geoip.db sing-box-${VERSION}-linux-amd64/geoip.db
          cd sing-box-${VERSION}-linux-amd64
          ./sing-box geoip export cn
          ./sing-box geoip export private
          ./sing-box geosite export cn
          ./sing-box rule-set compile geoip-cn.json
          ./sing-box rule-set compile geoip-private.json
          ./sing-box rule-set compile geosite-cn.json
          cp geoip-cn.json ../geoip-cn.json
          cp geoip-private.json ../geoip-private.json
          cp geosite-cn.json ../geosite-cn.json
          cp geoip-cn.srs ../geoip-cn.srs
          cp geoip-private.srs ../geoip-private.srs
          cp geosite-cn.srs ../geosite-cn.srs
          cd ..
      - name: Upload geosite and geoip as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geo
          path: |
            geosite.db
            geoip.db
            geoip-cn.json
            geoip-private.json
            geosite-cn.json
            geoip-cn.srs
            geoip-private.srs
            geosite-cn.srs
  release:
    permissions:
      contents: write
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Download geosite and geoip from artifacts
        uses: actions/download-artifact@v4
        with:
          name: geo
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "geosite.db,geoip.db,geoip-cn.json,geoip-private.json,geosite-cn.json,geoip-cn.srs,geoip-private.srs,geosite-cn.srs"
          prerelease: false
          tag: "2024-7"
