name: Release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.5'
      - name: Install geo
        run: go install -v github.com/metacubex/geo/cmd/geo@master
      - name: Download v2fly geosite and geoip
        run: |
          curl -L -o geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
          curl -L -o geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
      - name: Convert geosite and geoip to sing-box format
        run: |
          geo convert site -i v2ray -o sing -f geosite.db geosite.dat
          geo convert ip -i v2ray -o sing -f geoip.db geoip.dat
      - name: Make sing-rule-set
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.0-beta.2/sing-box-1.8.0-beta.2-linux-amd64.tar.gz
          tar -xf sing-box.tar.gz
          rm -rf sing-box.tar.gz
          cp geosite.db sing-box-1.8.0-beta.2-linux-amd64/geosite.db
          cp geoip.db sing-box-1.8.0-beta.2-linux-amd64/geoip.db
          cd sing-box-1.8.0-beta.2-linux-amd64
          ./sing-box geoip export cn
          ./sing-box geoip export private
          ./sing-box geosite export cn
          ./sing-box rule-set compile geoip-cn.json
          ./sing-box rule-set compile geoip-private.json
          ./sing-box rule-set compile geosite-cn.json
          cp geoip-cn.json ../geoip-cn.json
          cp geoip-private.json ../geoip-private.json
          cp geosite-cn.json ../geosite-cn.json
          cp geoip-cn.srs ../geoip-cn.srs
          cp geoip-private.srs ../geoip-private.srs
          cp geosite-cn.srs ../geosite-cn.srs
          cd ..
      - name: Upload geosite and geoip as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: geo
          path: |
            geosite.db
            geoip.db
            geoip-cn.json
            geoip-private.json
            geosite-cn.json
            geoip-cn.srs
            geoip-private.srs
            geosite-cn.srs
  release:
    permissions:
      contents: write
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Download geosite and geoip from artifacts
        uses: actions/download-artifact@v3
        with:
          name: geo
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: 2023-6
          files: |
            geosite.db
            geoip.db
            geoip-cn.json
            geoip-private.json
            geosite-cn.json
            geoip-cn.srs
            geoip-private.srs
            geosite-cn.srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
